version: "3.8"

services:
  wg-easy:
    image: hcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST=${IP_ADDRESS}  # Укажи внешний IP
      - PASSWORD=${PASSWORD}
      - WG_PORT=${WG_PORT}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./data/wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - wg-easy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:rw
    restart: unless-stopped